defaults:
  - all_dataset_config
  - _self_

mode : 'train'
database:
  database_path: '/pubdata/zhongjiafeng/ASVspoof_LA/'
  protocol_path: '/pubdata/zhongjiafeng/ASVspoof_LA/ASVspoof2019_LA_cm_protocols/'
  protocol:
    train: ???
    dev: ???
  track: 'LA'
  data_augment: False
  cut_length: 64600

reproducible:
  enable: True
  random_seed : 1234
  cudnn_deterministic_toggle: False
  cudnn_benchmark_toggle: True

model_configuration:
  model_name: 'Custom_model'
  load_checkpoint: False
  model_path: ???
  pretrain_path : ???
  ssl_freeze: True
  ssl_name: wavlm

training:
  num_gpus: 2
  batch_size: 64
  num_workers : 8
  shuffle : True
  drop_last: False
  max_num_epoch: 100
  loss : ???
  optimizer:
    scheduler: 'cosine'
    lr_min: 0.000005
    base_lr: 0.0001
    weight_decay: 0.0001
  eval_dataset : 'ASVspoof19LA'
  cut_length: ${database.cut_length}

log:
  comment: ???
  output: ???
  score_output: ???

across_evaluate:
  batch_size : 64
  num_workers : ${training.num_workers}
  cut_length: 64600
  phase : 'eval'
  enable_dataset: ['toy']

