defaults:
  - all_dataset_config
  - _self_

mode : 'train'

database:
  database_path: '/pubdata/zhongjiafeng/ADD2023/'
  protocol_path: '/pubdata/zhongjiafeng/ADD2023/'
  protocol:
    train: ???
    dev: ???
  track: 'LA'
  enable_data_augment_in_train: True
  cut_length: 64600

reproducible:
  enable: False
  random_seed : 1234
  cudnn_deterministic_toggle: True
  cudnn_benchmark_toggle: False

gen_configuration:
  upsample_rates: [8,8,2,2]
  upsample_kernel_sizes: [16,16,4,4]
  upsample_initial_channel: 512
  resblock_kernel_sizes: [3,7,11]
  resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]


training:
  num_gpus: 3
  batch_size: 108
  num_workers : 8
  shuffle : True
  drop_last: False
  max_num_epoch: 100
  loss : ???
  lr : 0.0002
  lr_decay: 0.999
  adam_beta: [0.8,0.99]
  schedule : ???
  eval_dataset : 'FMFCC_A'
  cut_length: ${database.cut_length}

