mode : eval
random_seed: 1234
num_gpus: 2

database:
  database_path: '/pubdata/zhongjiafeng/ADD2023/Track1/track1.2/'
  feature_path: "/pubdata/zhongjiafeng/ADD_cache/"
  protocol_path: '/home/zhongjiafeng/Model/N801/database/ADD2023-key/large/'
  protocol:
    train: ???
    dev: ???
  track: 'LA'
  enable_data_augment_in_train: True
  cut_length: 64600
  hand_feature: False
  normalization: True


model_configuration:
  model_name: wav2vec_resnet_normalization
  model_params: ???
  load_checkpoint: True
  model_path: /pubdata/zhongjiafeng/pretrain_model/wav2vec2.0-assist/LA_model.pth
  ssl_path : /pubdata/zhongjiafeng/self_supervise_model/wav2vec/xlsr2_300m.pt
  ssl_freeze: True
  ssl_name: XLSR

training:
  batch_size: 36
  num_workers : 4
  shuffle : True
  drop_last: False
  max_num_epoch: 100
  loss : ???
  optimizer:
    scheduler: cosine
    lr_min: 0.0000001
    base_lr: 0.00005
    weight_decay: 0.0001
  eval_dataset : 'ADD2023'
  cut_length: ${database.cut_length}
  validation_interval: 3

evaluate:
  batch_size : 128
  num_workers : 4
  cut_length: 64600
  hand_feature: False
  normalization: True

ADD2023_2:
  base_dir: '/pubdata/zhongjiafeng/ADD2023/Track1/wav/'
  protocol: '/home/zhongjiafeng/Model/N801/key/ADD2023-key/Track1_2_2_eval_key.txt'
  feature_dir : "/pubdata/zhongjiafeng/ADD_cache/eval/"


