# @package _name_
ASVspoof19LA:
  base_dir: '/pubdata/zhongjiafeng/ASVspoofLA/ASVspoof2019_LA_eval/'
  protocol: '/home/zhongjiafeng/Model/N801/database/19LA-keys/ASVspoof2019.LA.cm.eval.trl.txt'

ASVspoof21LA:
  base_dir: '/pubdata/zhongjiafeng/ASVspoofLA/ASVspoof2021_LA_eval/'
  protocol: '/home/zhongjiafeng/Model/N801/database/21LA-keys/keys/CM/trial_metadata.txt'

ASVspoof21DF:
  base_dir: '/pubdata/zhongjiafeng/ASVspoof2021_DF_eval/'
  protocol: '/home/zhongjiafeng/Model/N801/database/21DF-keys/keys/CM/trial_metadata.txt'

FMFCC_A:
  base_dir: '/pubdata/zhongjiafeng/FMACC/FMFCC-Adataset/'
  protocol: /home/zhongjiafeng/Model/N801/key/FMFCC-A-keys/FMFCC-key.txt

toy:
  base_dir: '/pubdata/zhongjiafeng/Compressdataset/toy_large_ogg_16k/'
  protocol: '/pubdata/zhongjiafeng/Compressdataset/toy_large/sam_from_ASVspoof19_label.txt'

ADD2023_1:
  base_dir: '/pubdata/zhongjiafeng/ADD2023/Track1/track1.2/wav/'
  protocol: '/home/zhongjiafeng/Model/N801/key/ADD2023-key/Track1_2_1_eval_key.txt'
  feature_dir : "/pubdata/zhongjiafeng/ADD_cache/eval/"

ADD2023_2:
  base_dir: '/pubdata/zhongjiafeng/ADD2023/Track1/wav/'
  protocol: '/home/zhongjiafeng/Model/N801/key/ADD2023-key/Track1_2_2_eval_key.txt'
  feature_dir : "/pubdata/zhongjiafeng/ADD_cache/eval/"