defaults:
  - all_dataset_config
  - _self_

mode : 'eval'
database:
  database_path: '/pubdata/zhongjiafeng/ASVspoof_LA/'
  protocol_path: '/pubdata/zhongjiafeng/ASVspoof_LA/ASVspoof2019_LA_cm_protocols/'
  protocol:
    train: ???
    dev: ???
  track: 'LA'
  enable_data_augment_in_train: True
  cut_length: 64600


reproducible:
  enable: True
  random_seed : 1234
  cudnn_deterministic_toggle: False
  cudnn_benchmark_toggle: True

model_configuration:
  model_name: 'wav2vec-ASSIST'
  load_checkpoint: False
  model_path: '/home/zhongjiafeng/Model/N801/pretrain/wav2vec2.0-assist/without_DA'
  pretrain_path : '/pubdata/zhongjiafeng/pretrain_model/wav2vec/xlsr2_300m.pt'

training:
  num_gpus: 3
  batch_size: 12
  num_workers : 4
  shuffle : True
  drop_last: False
  max_num_epoch: 3
  loss : ???
  lr : 0.00001
  weight_decay: 0.0001
  optimzer : ???
  schedule : ???
  eval_dataset : 'ASVspoof19LA'
  cut_length: ${database.cut_length}

log:
  comment: ???
  output: ???
  score_output: ???

across_evaluate:
  batch_size : 64
  num_workers : ${training.num_workers}
  cut_length: 64600
  phase : 'eval'
  enable_dataset: ['ADD2023']

